name: KSR-OITC
main: ch.ksrminecraft.kSROITC.KSROITC
version: ${project.version}   # <- wird durch Maven gefiltert
api-version: '1.21'
commands:
  oitc:
    description: One in the Chamber – Hauptbefehl
    usage: /oitc <...>
permissions:
  oitc.use:
    default: true
  oitc.admin:
    default: op